/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.serious.orders.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Honey service. Represents a row in the &quot;manager_odr_Honey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.serious.orders.model.impl.HoneyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.serious.orders.model.impl.HoneyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Honey
 * @generated
 */
@ProviderType
public interface HoneyModel extends BaseModel<Honey> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a honey model instance should use the {@link Honey} interface instead.
	 */

	/**
	 * Returns the primary key of this honey.
	 *
	 * @return the primary key of this honey
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this honey.
	 *
	 * @param primaryKey the primary key of this honey
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this honey.
	 *
	 * @return the ID of this honey
	 */
	public long getId();

	/**
	 * Sets the ID of this honey.
	 *
	 * @param id the ID of this honey
	 */
	public void setId(long id);

	/**
	 * Returns the type of this honey.
	 *
	 * @return the type of this honey
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this honey.
	 *
	 * @param type the type of this honey
	 */
	public void setType(String type);

	/**
	 * Returns the price of this honey.
	 *
	 * @return the price of this honey
	 */
	public int getPrice();

	/**
	 * Sets the price of this honey.
	 *
	 * @param price the price of this honey
	 */
	public void setPrice(int price);

	/**
	 * Returns the stock of this honey.
	 *
	 * @return the stock of this honey
	 */
	public boolean getStock();

	/**
	 * Returns <code>true</code> if this honey is stock.
	 *
	 * @return <code>true</code> if this honey is stock; <code>false</code> otherwise
	 */
	public boolean isStock();

	/**
	 * Sets whether this honey is stock.
	 *
	 * @param stock the stock of this honey
	 */
	public void setStock(boolean stock);

}