/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.serious.orders.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OrderInfo service. Represents a row in the &quot;manager_odr_OrderInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.serious.orders.model.impl.OrderInfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.serious.orders.model.impl.OrderInfoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrderInfo
 * @generated
 */
@ProviderType
public interface OrderInfoModel extends BaseModel<OrderInfo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order info model instance should use the {@link OrderInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this order info.
	 *
	 * @return the primary key of this order info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order info.
	 *
	 * @param primaryKey the primary key of this order info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this order info.
	 *
	 * @return the ID of this order info
	 */
	public long getId();

	/**
	 * Sets the ID of this order info.
	 *
	 * @param id the ID of this order info
	 */
	public void setId(long id);

	/**
	 * Returns the orderid of this order info.
	 *
	 * @return the orderid of this order info
	 */
	public long getOrderid();

	/**
	 * Sets the orderid of this order info.
	 *
	 * @param orderid the orderid of this order info
	 */
	public void setOrderid(long orderid);

	/**
	 * Returns the type of this order info.
	 *
	 * @return the type of this order info
	 */
	public long getType();

	/**
	 * Sets the type of this order info.
	 *
	 * @param type the type of this order info
	 */
	public void setType(long type);

	/**
	 * Returns the amount of this order info.
	 *
	 * @return the amount of this order info
	 */
	public int getAmount();

	/**
	 * Sets the amount of this order info.
	 *
	 * @param amount the amount of this order info
	 */
	public void setAmount(int amount);

}