/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.serious.orders.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Order service. Represents a row in the &quot;manager_odr_Order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.serious.orders.model.impl.OrderModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.serious.orders.model.impl.OrderImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Order
 * @generated
 */
@ProviderType
public interface OrderModel extends BaseModel<Order> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order model instance should use the {@link Order} interface instead.
	 */

	/**
	 * Returns the primary key of this order.
	 *
	 * @return the primary key of this order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order.
	 *
	 * @param primaryKey the primary key of this order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this order.
	 *
	 * @return the ID of this order
	 */
	public long getId();

	/**
	 * Sets the ID of this order.
	 *
	 * @param id the ID of this order
	 */
	public void setId(long id);

	/**
	 * Returns the date order of this order.
	 *
	 * @return the date order of this order
	 */
	public Date getDateOrder();

	/**
	 * Sets the date order of this order.
	 *
	 * @param dateOrder the date order of this order
	 */
	public void setDateOrder(Date dateOrder);

	/**
	 * Returns the customer of this order.
	 *
	 * @return the customer of this order
	 */
	@AutoEscape
	public String getCustomer();

	/**
	 * Sets the customer of this order.
	 *
	 * @param customer the customer of this order
	 */
	public void setCustomer(String customer);

	/**
	 * Returns the status of this order.
	 *
	 * @return the status of this order
	 */
	public int getStatus();

	/**
	 * Sets the status of this order.
	 *
	 * @param status the status of this order
	 */
	public void setStatus(int status);

	/**
	 * Returns the address of this order.
	 *
	 * @return the address of this order
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this order.
	 *
	 * @param address the address of this order
	 */
	public void setAddress(String address);

}