/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.serious.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Orders service. Represents a row in the &quot;my_orders_Orders&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.serious.model.impl.OrdersModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.serious.model.impl.OrdersImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Orders
 * @generated
 */
@ProviderType
public interface OrdersModel extends BaseModel<Orders> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a orders model instance should use the {@link Orders} interface instead.
	 */

	/**
	 * Returns the primary key of this orders.
	 *
	 * @return the primary key of this orders
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this orders.
	 *
	 * @param primaryKey the primary key of this orders
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this orders.
	 *
	 * @return the ID of this orders
	 */
	public long getId();

	/**
	 * Sets the ID of this orders.
	 *
	 * @param id the ID of this orders
	 */
	public void setId(long id);

	/**
	 * Returns the date order of this orders.
	 *
	 * @return the date order of this orders
	 */
	public Date getDateOrder();

	/**
	 * Sets the date order of this orders.
	 *
	 * @param dateOrder the date order of this orders
	 */
	public void setDateOrder(Date dateOrder);

	/**
	 * Returns the customer of this orders.
	 *
	 * @return the customer of this orders
	 */
	@AutoEscape
	public String getCustomer();

	/**
	 * Sets the customer of this orders.
	 *
	 * @param customer the customer of this orders
	 */
	public void setCustomer(String customer);

	/**
	 * Returns the orderinfo of this orders.
	 *
	 * @return the orderinfo of this orders
	 */
	public long getOrderinfo();

	/**
	 * Sets the orderinfo of this orders.
	 *
	 * @param orderinfo the orderinfo of this orders
	 */
	public void setOrderinfo(long orderinfo);

	/**
	 * Returns the status of this orders.
	 *
	 * @return the status of this orders
	 */
	public int getStatus();

	/**
	 * Sets the status of this orders.
	 *
	 * @param status the status of this orders
	 */
	public void setStatus(int status);

}